/**
 * BannerPromptService — generate an optimised Imagen 3 prompt from a high-level
 * banner brief (campaign objective, brand, audience, etc.).
 *
 * Provider requirement: "text-generation" (satisfied by GeminiProvider).
 *
 * Step 1 of the two-step banner pipeline:
 *   1. BannerPromptService   — brief → optimised Imagen 3 prompt  (this file)
 *   2. BannerGenerationService — prompt → banner image             (banner-generation.ts)
 *
 * The service sends the brief (and an optional reference image) to Gemini and
 * receives a JSON response with `optimizedPrompt` + `negativePrompt`.
 * If JSON parsing fails, the raw response text is used as the prompt.
 */

import type { GenerateRequest, GenerateResponse, AIContentPart } from "../types";
import { AIService } from "./base";
import { ParseError } from "../errors";
import { extractJson } from "@/lib/llm-client";

// ── Input / Output types ──────────────────────────────────────────────────────

export interface BannerPromptInput {
  campaignObjective: string;
  promotion?: string;
  brand?: string;
  targetAudience?: string;
  platform?: string;
  language?: string;
  visualStyle?: string;
  dimensions: { width: number; height: number };
  brandGuideline?: unknown;
  referenceImageDataUrl?: string;
}

export interface BannerPromptOutput {
  optimizedPrompt: string;
  negativePrompt?: string;
}

// ── Service ───────────────────────────────────────────────────────────────────

export class BannerPromptService extends AIService<BannerPromptInput, BannerPromptOutput> {
  readonly serviceName      = "BannerPromptService";
  readonly requiredCapability = "text-generation" as const;

  protected buildRequest(input: BannerPromptInput): GenerateRequest {
    const textContent = buildTextContent(input);

    if (input.referenceImageDataUrl) {
      const content: AIContentPart[] = [
        { type: "image", imageDataUrl: input.referenceImageDataUrl },
        {
          type: "text",
          text: `Use the visual style of this reference image as inspiration for the banner design.\n\n${textContent}`,
        },
      ];
      return {
        messages: [{ role: "user", content }],
        maxTokens: 1024,
        temperature: 0.7,
      };
    }

    return {
      messages: [{ role: "user", content: textContent }],
      maxTokens: 1024,
      temperature: 0.7,
    };
  }

  protected parseResponse(
    response: GenerateResponse,
    _input: BannerPromptInput,
  ): BannerPromptOutput {
    const parsed = extractJson(response.text);

    if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
      const obj = parsed as Record<string, unknown>;
      if (typeof obj.optimizedPrompt === "string" && obj.optimizedPrompt.trim()) {
        return {
          optimizedPrompt: obj.optimizedPrompt.trim(),
          negativePrompt:
            typeof obj.negativePrompt === "string" ? obj.negativePrompt.trim() : undefined,
        };
      }
    }

    // Fallback: use raw response text as the prompt
    const fallback = response.text.trim();
    if (!fallback) throw new ParseError("Empty prompt response from provider", "gemini");
    return { optimizedPrompt: fallback };
  }
}

// ── Prompt builder ────────────────────────────────────────────────────────────

function buildTextContent(input: BannerPromptInput): string {
  const { width, height } = input.dimensions;

  // Extract brand colors from the guideline if present
  const bg = input.brandGuideline as Record<string, unknown> | undefined;
  const brandColors: string[] = [];
  if (bg?.colors) {
    const c = bg.colors as Record<string, unknown>;
    const primary   = (c.primary   as { hex?: string } | undefined)?.hex;
    const secondary = (c.secondary as { hex?: string } | undefined)?.hex;
    if (primary)   brandColors.push(primary);
    if (secondary) brandColors.push(secondary);
  }
  const paletteHint = brandColors.length
    ? brandColors.join(", ")
    : "#0033C9 (deep blue), #00CF6A (vibrant green), white";

  const lines: string[] = [
    "You are an expert visual art director and advertising photographer specializing in Vietnamese fintech brands.",
    "Your task: write ONE detailed scene description that will be used as an AI image generation prompt",
    "for a ZaloPay advertising banner. The image will be generated by a commercial-grade AI image model.",
    "",
    "ZALOPAY BRAND CONTEXT (inject automatically into every prompt):",
    `- Brand colors: ${paletteHint}`,
    "- Brand essence: modern, trustworthy, convenient Vietnamese digital payments",
    "- Visual identity: clean compositions, premium lifestyle photography, warm Vietnamese context",
    "- Mandatory visual elements: ZaloPay brand colors visible in scene (clothing, props, UI, backgrounds)",
    "- People: young Vietnamese urban professionals, age 20–35, modern city lifestyle",
    "- Phone/device: modern smartphone prominently featured displaying ZaloPay payment UI",
    "- Photography quality: premium commercial advertising, magazine cover quality, soft natural bokeh",
    "",
    "ADVERTISING CAMPAIGN BRIEF:",
    `- Campaign objective: ${input.campaignObjective}`,
  ];

  if (input.promotion?.trim())      lines.push(`- Promotion / offer: ${input.promotion}`);
  if (input.brand?.trim())          lines.push(`- Brand: ${input.brand}`);
  if (input.targetAudience?.trim()) lines.push(`- Target audience: ${input.targetAudience}`);
  if (input.platform?.trim())       lines.push(`- Platform: ${input.platform}`);
  if (input.language)               lines.push(`- Language context: ${input.language === "vi" ? "Vietnamese — Vietnam setting, Vietnamese faces" : "English — international urban setting"}`);
  if (input.visualStyle?.trim())    lines.push(`- Visual style direction: ${input.visualStyle}`);
  if (bg?.brandName)                lines.push(`- Featured brand: ${String(bg.brandName)}`);

  lines.push(
    `- Canvas dimensions: ${width}×${height}px`,
    "",
    "COMPOSITION REQUIREMENTS:",
    "- Clear visual hierarchy: one dominant hero subject, supporting environmental context",
    "- Natural breathing space on sides and bottom for text overlay (CTA button area)",
    "- Warm, aspirational lighting — golden hour, soft window light, or studio-quality ambient",
    "- ZaloPay app UI visible on device screen showing a successful payment or transaction",
    "- Vietnamese street scenes, modern cafes, homes, or lifestyle settings as environment",
    "- Avoid: text in scene, logos, watermarks, overly staged corporate look",
    "",
    "OUTPUT RULES:",
    "- Write ONLY a pure visual scene description in English",
    "- Do NOT include quality descriptors (4K, photorealistic, HD) — those are added automatically",
    "- Do NOT include aspect ratio or canvas size — those are handled by the pipeline",
    "- Do NOT include negative prompts in optimizedPrompt",
    "- Keep the optimizedPrompt under 180 words",
    "",
    "Return ONLY a JSON object — no markdown fences, no explanation:",
    `{"optimizedPrompt": "…pure visual scene description…", "negativePrompt": "blurry, distorted text, watermark, ugly composition, amateurish, grainy, oversaturated, deformed hands, duplicate elements"}`,
  );

  return lines.join("\n");
}
